# Generated by Django 4.2.5 on 2023-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_item_deadline_list_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='List completed at', null=True),
        ),
    ]
